# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache:
  - packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - libgdal-dev
      - libproj-dev
      - libboost1.67-all-dev
      - libfftw3-dev
      - libqwt-dev

env:
  - CC=gcc-8
        
before_install:
  - mkdir -p zonation4
  - cd zonation4
  - git clone https://github.com/cbig/zonation-core
  - mkdir build
  - cd build
  - cmake ../zonation-core
  - make
  - ln -sf /home/travis/zonation4/build/zig4 /home/travis/bin/zig4
  - cd $WORKDIR

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel
